<?php
namespace LSECitiesWPTheme;

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

if(!defined('SECTION_FRONTS_PODS_NAME')) {
  define('SECTION_FRONTS_PODS_NAME', 'section_front');
}

class SectionFront extends PodsObject {
  const PODS_NAME = SECTION_FRONTS_PODS_NAME;
  
  // TECHNICAL_DEBT: this shouldn't be hardcode here; moreover this
  // way of managing tiles is going to disappear as part of #102
  const TILES_PER_COLUMN = 2;
  
  public $permalink;
  
  /**
   * Content associated to research project (events, publications,
   * posts, data visualizations, other outputs...)
   */
  /**
   * @var Array Events associated to a research project
   */
  public $linked_events;
  
  /**
   * @var String Twitter timeline ID - used to generate a Twitter
   *   widget HTML fragment based on the timeline ID associated to
   *   a Twitter timeline (https://dev.twitter.com/web/embedded-timelines/search)
   */
  public $twitter_embedded_timeline_id;
  
  /**
   * @var Array Permalinks of WP post categories associated to this
   *   section front; list of news items is generated by querying
   *   (WP_Query) across these categories.
   * TECHNICAL_DEBT: We could probably avoid having this as a class
   * member variable if we only use it to generate the actual list of
   * posts (news_items).
   */
  public $news_categories;
  
  /**
   * @var Array News items associated to this section front, split
   *   between primary (displayed with an excerpt) and secondary (only
   *   dates and titles are displayed). The list of items is generated
   *   by querying the most recent posts across the news_categories
   *   associated to the section front.
   */
  public $news_items;
  
  public $flexslider_configuration;
  public $slides;
  
  public $latest_update;
    
  /**
   * @var Object The Pod object for this SectionFront
   */
  private $pod;
  
  function __construct($permalink) {
    $this->pod = $pod = pods(self::PODS_NAME, $permalink);
    
    // return if a Pod cannot be found
    if(!$pod->exists()) {
      return;
    }

    $this->permalink = $permalink;
    
    // TECHNICAL_DEBT: do we still need this? (backported from non-OO code)
    // TECHNICAL_DEBT: moreover, we shouldn't mix global state in here
    // for menus etc.
    global $this_pod;
    $this_pod = new \LC\PodObject($pod, 'Frontpage');
  
    // TECHNICAL_DEBT: we should avoid mixing global state in object constructor
    $this->latest_update = lc_data('META_last_modified', $pod->field('modified'));
    
    $this->twitter_embedded_timeline_id = $pod->field('twitter_embedded_timeline_id');
    
    $this->news_categories = $pod->field('news_categories.term_id');
    $this->news_items = $this->get_linked_news();
    
    /**
     * Read any jquery options and set global variable accordingly; these
     * options are used in the footer.php template.
     * These options need to be stored as valid JSON; as this JSON
     * fragment is ultimately used in an HTML5 data attribute and then
     * parsed by jQuery.data() via jQuery.parseJSON(), but MtHAML outputs
     * HTML attributes delimited by double quotes ("), we need to first
     * replace here all the JSON double quotes with single quotes so that
     * JSON is 'correctly' stored as data attribute, then in the JS code
     * we replace back all single quotes with double quotes before
     * loading the JSON fragment...
     * Twisted, but that's the only way i can think of.
     */
    $this->flexslider_configuration = str_replace('"', "'", $pod->field('flexslider_configuration'));
    
    $slides = sort_linked_field($pod->field('slides'), 'displayorder', SORT_ASC);
    
    if(is_array($slides)) {
      foreach($slides as $slide) {
        $this->slides[] = $this->compose_slide($slide['slug']);
      }
    }

    $this->linked_events = sort_linked_field($pod->field('linked_events'), 'date_start', SORT_DESC);
  }

  /**
   * Return x and y size of a tile, given its layout
   * Tile layouts are strings with format XxY, with 1 <= X < 5= and 1 <= Y <= 2
   * @param String $tile_layout The tile layout
   * @return Array An array with x and y sizes: [X, Y]
   */
  function get_tile_size($tile_layout) {
    $xcount = substr($tile_layout, 0, 1);
    $ycount = substr($tile_layout, -1);
    
    return [ $xcount, $ycount ];
  }

  function get_tile_classes($tile_layout) {
    $element_classes = '';

    list($xcount, $ycount) = $this->get_tile_size($tile_layout);

    switch($xcount) {
      case '1':
        $element_classes .= 'onetile';
        break;
      case '2':
        $element_classes .= 'twotiles';
        break;
      case '3':
        $element_classes .= 'threetiles';
        break;
      case '4':
        $element_classes .= 'fourtiles';
        break;
      case '5':
        $element_classes .= 'fivetiles';
        break;
    }

    switch($ycount) {
      case '2':
        $element_classes .= ' tall';
        break;
    }

    return $element_classes;
  }

  function compose_slide($slide_slug) {
    $current_slide_pod = pods('slide', $slide_slug);
    $slide_layout = $current_slide_pod->field('slide_layout.slug');

    /**
     * build array of slides for this tile by reading in sequence
     * all the tile_NN fields of the slide Pod (initially these are 8)
     */
    $tiles = array();
    foreach(array(0, 1, 2, 3, 4, 5, 6, 7) as $tile_counter) {
      $this_tile_slug = $current_slide_pod->field('tile_' . sprintf('%02d', $tile_counter) . '.slug');
      array_push($tiles, array('slug' => $this_tile_slug));
    }

    var_trace('tiles: ' . var_export($tiles, true), $TRACE_PREFIX);
    var_trace('slide_layout: ' . var_export($slide_layout, true), $TRACE_PREFIX);

    switch($slide_layout) {
      case 'two-two-one':
        $slide_content = $this->compose_slide_content([2, 2, 1], $tiles);
        var_trace(var_export($slide_content, true), 'slide_content_array');
        break;
      case 'four-one':
        $slide_content = $this->compose_slide_content([4, 1], $tiles);
        var_trace(var_export($slide_content, true), 'slide_content_array');
        break;
      case 'five':
        $slide_content = $this->compose_slide_content([5], $tiles);
        var_trace(var_export($slide_content, true), 'slide_content_array');
        break;
      default:
        break;
    }

    return $slide_content;
  }

  function compose_slide_content($column_spans, $tiles) {
    var_trace(var_export($tiles, true), 'compose_slide|tiles');

    $slide_content = [ 'columns' => [] ];
    $tile_index = 0;
    $total_tiles = count($tiles);

    var_trace('column_spans: ' . var_export($column_spans, true), $TRACE_PREFIX);

    foreach($column_spans as $key => $column_span) {
      $tile_count = $column_span * self::TILES_PER_COLUMN;

      // add .last class if this is the last column
      if($key == (count($column_spans) - 1)) { $last_class = ' last'; }

      $slide_column = [ 'layout' => 'col' . $column_span . $last_class, 'tiles' => [] ];
      
      while($tile_count > 0 and $tile_index <= $total_tiles) {
        var_trace(var_export($tiles[$tile_index]['slug'], true), 'tile[slug]');
        $tile = pods('tile', $tiles[$tile_index++]['slug']);
        $tile_layout = $tile->field('tile_layout.name');
        $tile_xcount = $this->get_tile_size($tile_layout)[0];
        var_trace(var_export($tile_layout, true), 'tile[layout]');
        $this_tile_count = preg_replace('/x/', '*', $tile_layout);
        var_trace(var_export($this_tile_count, true), 'this_tile_count');
        eval('$this_tile_count = ' . $this_tile_count . ';');
        $tile_count -= $this_tile_count;
        var_trace(var_export($tile_count, true), 'tile_countdown');

        unset($target_event_month, $target_event_day, $target_uri);

        if($tile->field('target_event.date_start')) {
          $target_event_date = new \DateTime($tile->field('target_event.date_start'));
          var_trace('target_event_date: ' . var_export($target_event_date, true), $TRACE_PREFIX);
          $target_event_month = $target_event_date->format('M');
          $target_event_day = $target_event_date->format('j');
          $target_event_slug = $tile->field('target_event.slug');
        }

        if($tile->field('target_event.slug')) {
          $target_uri = PODS_BASEURI_EVENTS . '/' . $tile->field('target_event.slug');
        } elseif($tile->field('target_research_project')) {
          $target_uri = PODS_BASEURI_RESEARCH_PROJECTS . '/' . $tile->field('target_research_project.slug');
        } elseif($tile->field('target_uri')) {
          $target_uri = $tile->field('target_uri');
        } elseif($tile->field('target_page.ID')) {
          $target_uri = get_permalink($tile->field('target_page.ID'));
        } elseif($tile->field('target_post.ID')) {
          $target_uri = get_permalink($tile->field('target_post.ID'));
        } else {
          $target_uri = null;
        }

        /**
         * Add image attribution metadata if present in media item
         */
        $image_attribution = format_media_attribution(get_media_attribution($tile->field('image.id')));

        // Read tile title, subtitle (tagline) and blurb
        $tile_title = $tile->field('name');
        $tile_tagline = $tile->field('tagline');
        $tile_blurb = $tile->field('blurb');
      
        // If no blurb is set, set relevant tile property to be used in element classes
        $noblurb_class = empty($tile_blurb) ? 'noblurb' : '';

        $slide_column['tiles'][] = [
          'id' => $tile->field('slug'),
          'element_class' => rtrim($this->get_tile_classes($tile_layout) . ' ' . $tile->field('class'), ' '),
          'noblurb_class' => $noblurb_class,
          'title' => $tile_title,
          'display_title' => $tile->field('display_title'),
          'subtitle' => $tile_tagline,
          'blurb' => $tile_blurb,
          'plain_content' => wpautop($tile->field('plain_content')),
          'posts_category' => $tile->field('posts_category.term_id'),
          'target_uri' => $target_uri,
	  // 500px times column spans; height = 9999 is to keep ratio as per
	  // https://developer.wordpress.org/reference/functions/add_image_size/,
          // section 'Other Notes'
          'image' => pods_image_url($tile->field('image.ID'), [ $tile_xcount * 500 , 9999 ]),
          'image_attribution' => $image_attribution,
          'target_event' => [
            'month' => $target_event_month,
            'day' => $target_event_day
          ]
        ];
      }
      
      $slide_content['columns'][] = $slide_column;
    }
    
    return $slide_content;
  }
  
  function get_linked_news() {
    if(!empty($this->news_categories)) {
      $posts = [
        'primary' => [],
        'secondary' => []
      ];
      
      if($this->twitter_embedded_timeline_id) {
        $primary_news_items_count = 2;
      } else {
        $primary_news_items_count = 3;
      }
      
      $secondary_news_items_count = 10 + $primary_news_items_count;
      
      $wp_primary_query = [
        'posts_per_page' => $primary_news_items_count,
        'category__in' => $this->news_categories
      ];

      $wp_secondary_query = [
        'posts_per_page' => $secondary_news_items_count,
        'category__in' => $this->news_categories
      ];
      
      $index_of_last_primary_news_item = $primary_news_items_count > 0 ? $primary_news_items_count - 1 : 0;

      $primary_news = new \WP_Query($wp_primary_query);

      while ($primary_news->have_posts()) {
        $primary_news->the_post();
        
        $posts['primary'][] = [
          'date' => [
            'year' => get_the_time('Y'),
            'month' => get_the_time('M'),
            'day' => get_the_time('j')
          ],
          'permalink' => get_permalink(),
          'title' => get_the_title(),
          'excerpt' => get_the_excerpt()
        ];
      }
      
      wp_reset_postdata();

      $secondary_news = new \WP_Query($wp_secondary_query);

      if($secondary_news->found_posts > $primary_news_items_count) {
        while ($secondary_news->have_posts()) {
          $secondary_news->the_post();
          
          if ($secondary_news->current_post > $index_of_last_primary_news_item) {
            $posts['secondary'][] = [
              'date' => [
              'year' => get_the_time('Y'),
              'month' => get_the_time('M'),
              'day' => get_the_time('j')
            ],
            'permalink' => get_permalink(),
            'title' => get_the_title(),
            'excerpt' => get_the_excerpt()
            ];
          }
        }
      }
      
      wp_reset_postdata();

      return $posts;
      
    } else {
      return NULL;
    }
  }
}
